version: '3.3'
services:
  rabbitmq:
    container_name: vcms-svc-rabbitmq
    image: rabbitmq:3.10.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - configuration-rabbit-mq.env
  postgres:
    container_name: vcms-svc-postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    hostname: vcms-svc-postgres
    env_file:
      - configuration-postgres.env
  aries-facade:
    container_name: vcms-svc-aries-facade
    image: vcmsregistry.azurecr.io/vcms-svc-aries-facade:0.9.0.20221130T082004Z
    ports:
      - "8000:8000"
    env_file:
      - configuration-aries-facade.env
      - configuration-rabbit-mq.env
  tails-file-server:
    container_name: vcms-svc-tails
    image: vcmsregistry.azurecr.io/vcms-svc-tails-server:0.9.0.20221130T082004Z
    ports:
      - "6543:6543"
    hostname: vcms-svc-tails-server
    env_file:
      - configuration-tails-server.env
    volumes:
      - ./tails-files:/tmp/tails-files
  connector:
    container_name: vcms-api-connector
    image: vcmsregistry.azurecr.io/vcms-api-connector:0.9.0.20221130T082004Z
    ports:
      - "8080:8080"
    depends_on:
      - "aca-py"
      - "rabbitmq"
    env_file:
      - configuration-connector.env
      - configuration-rabbit-mq.env
  aca-py:
    container_name: vcms-svc-aca-py
    image: vcmsregistry.azurecr.io/vcms-svc-aca-py:0.9.0.20221130T082004Z
    ports:
      - "9020:9020"
      - "8044:8044"
    env_file:
      - configuration-aca-py.env
    depends_on:
      - tails-file-server
    volumes:
      - ./wallet/:/home/indy/.indy_client
  webhook:
    container_name: vcms-svc-webhook
    image: vcmsregistry.azurecr.io/vcms-svc-webhook:0.9.0.20221130T082004Z
    ports:
      - "5001:5000"
    env_file:
      - configuration-webhook.env
      - configuration-rabbit-mq.env
  verifierserver:
    container_name: vcms-api-verifier
    image: vcmsregistry.azurecr.io/vcms-api-verifier:0.9.0.20221130T082004Z
    ports:
      - "8081:8081"
    hostname: vcms-api-verifier
    depends_on:
      - "aca-py"
      - "rabbitmq"
    env_file:
      - configuration-verifier-server.env
      - configuration-rabbit-mq.env
  issuerserver:
    container_name: vcms-api-issuer
    image: vcmsregistry.azurecr.io/vcms-api-issuer:0.9.0.20221130T082004Z
    ports:
      - "8100:8100"
    hostname: vcms-api-issuer
    depends_on:
      - "rabbitmq"
    env_file:
      - configuration-issuer-server.env
      - configuration-rabbit-mq.env
  issuerclient:
    container_name: vcms-ui-issuer
    image: vcmsregistry.azurecr.io/vcms-ui-issuer:0.9.0.20221130T082004Z
    ports:
      - "81:80"
    hostname: vcms-ui-issuer
    volumes:
      - ./configuration-issuer-frontend.json:/dist/assets/environment-config.json
  verifierclient:
    container_name: vcms-ui-verifier
    image: vcmsregistry.azurecr.io/vcms-ui-verifier:0.9.0.20221130T082004Z
    ports:
      - "83:80"
    hostname: vcms-ui-verifier
    volumes:
      - ./configuration-verifier-frontend.json:/dist/assets/environment-config.json
